---
Name: selected-colour-picker
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/selected-colour-picket: client/dist/styles/main.css'

SilverStripe\Core\Injector\Injector:
  Colour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\DBColour
  FontColour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\FontColour
  BackgroundColour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\BackgroundColour


