---
Name: selected-colour-picker
---


SilverStripe\Core\Injector\Injector:
  Colour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\DBColour


SilverStripe\Core\Injector\Injector:
  FontColour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\FontColour

SilverStripe\Core\Injector\Injector:
  BackgroundColour:
    class: Sunnysideup\SelectedColourPicker\Model\Fields\BackgroundColour
